In [2]:
''' Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 
 İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 
 Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 
 Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir.'''

' Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. \n İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. \n Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır \n Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir.'

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5], dtype=int)

print("Arrayin boyutu:", arr1.ndim)

print("Arraydeki eleman sayısı:", arr1.size)

print("Arrayin şekli:", arr1.shape)


Arrayin boyutu: 1
Arraydeki eleman sayısı: 5
Arrayin şekli: (5,)


In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("İki boyutlu arrayin boyutu:", arr2.ndim)

print("İki boyutlu arrayin eleman sayısı:", arr2.size)

print("İki boyutlu arrayin şekli:", arr2.shape)


İki boyutlu arrayin boyutu: 2
İki boyutlu arrayin eleman sayısı: 6
İki boyutlu arrayin şekli: (2, 3)


In [5]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Üç boyutlu arrayin boyutu:", arr3.ndim)

print("Üç boyutlu arrayin eleman sayısı:", arr3.size)

print("Üç boyutlu arrayin şekli:", arr3.shape)


Üç boyutlu arrayin boyutu: 3
Üç boyutlu arrayin eleman sayısı: 8
Üç boyutlu arrayin şekli: (2, 2, 2)


In [6]:
print("İki boyutlu arrayin [1,2] elemanı:", arr2[1, 2])

print("İki boyutlu arrayin ilk satırı:", arr2[0, :])

İki boyutlu arrayin [1,2] elemanı: 6
İki boyutlu arrayin ilk satırı: [1 2 3]


In [8]:
print("Üç boyutlu arrayin [1,0,1] elemanı:", arr3[1, 0, 1])

print("Üç boyutlu arrayin ilk 'katmanı':", arr3[0, :, :])


Üç boyutlu arrayin [1,0,1] elemanı: 6
Üç boyutlu arrayin ilk 'katmanı': [[1 2]
 [3 4]]


In [9]:
zeros_array = np.zeros((2, 3), dtype=int)
print("Sıfırlardan oluşan array:\n", zeros_array)


Sıfırlardan oluşan array:
 [[0 0 0]
 [0 0 0]]


In [10]:
ones_array = np.ones((2, 3), dtype=int)
print("Birlerden oluşan array:\n", ones_array)


Birlerden oluşan array:
 [[1 1 1]
 [1 1 1]]


In [11]:
vertical_stack = np.vstack((zeros_array, ones_array))
print("Satır bazında birleştirilmiş array:\n", vertical_stack)

Satır bazında birleştirilmiş array:
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]


In [12]:
horizontal_stack = np.hstack((zeros_array, ones_array))
print("Sütun bazında birleştirilmiş array:\n", horizontal_stack)


Sütun bazında birleştirilmiş array:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
